-- auto Generated on 2020-05-13
-- DROP TABLE IF EXISTS company;
CREATE TABLE company(
	id INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
	company_name VARCHAR (50) NOT NULL DEFAULT '' COMMENT '名称',
	address VARCHAR (50) NOT NULL DEFAULT '' COMMENT '地址',
	crated_at DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT '创建时间',
	updated_at DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT '更新时间',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'company';
